apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: LINUXtips-labs
  region: eu-central-1
  
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
