apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: giropops
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: ngix
  dnsPolicy: ClusterFirst
  restartPolicy: Always
